add_newline = true
command_timeout = 2000

[character]
success_symbol = "ğŸ¡"
error_symbol = "ğŸ‘¹"

[line_break]
disabled = false

[status]
disabled = false

[time]
disabled = false
time_format = "%m%dT%H:%M:%S"
format = "ğŸ•˜[$time]($style)"

[directory]
truncation_symbol = ".../"

[git_branch]
symbol = "ğŸŒ±"

[gcloud]
format = "$directory[$symbol$active]($style)"

[golang]
format = "$directory[$symbol$version](bold cyan)"

