add_newline = false

[character]
success_symbol = "ğŸ¡"
error_symbol = "ğŸ‘¹"

[git_branch]
symbol = "ğŸŒ±"

[gcloud]
format = "$directory[$symbol$active]($style)"

[golang]
format = "$directory[go$version](bold cyan)"

